branch-defaults:
  master:
    environment: gratus
global:
  application_name: gratus
  default_ec2_keyname: gratus
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
